routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resources([
    'user' => 'UserController'
]);

app/Models/Users.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use DB;

class Users extends Model
{
    public $fillable = [
        'name',
        'email',
        'password'
    ];

    public function addNewUser($userData, $userInfoData)
    {
        DB::beginTransaction();
        try {
            $user = Users::create($userData);
            if ($user) {
                $userInfoData['user_id'] = $user->id; 
                if (Userinfoes::create($userInfoData)) {
                    DB::commit();

                    return 1;
                }
            }
        } catch (\Throwable $th) {
            DB::rollBack();

            throw $th;
        }
    }

    public function userInfo()
    {
        return $this->hasOne(Userinfoes::class, 'user_id');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Countries;
use App\Models\Users;
use App\Models\Userinfoes;
use App\Models\States;
use Illuminate\Http\Request;
use DB;

class UserController extends Controller
{
    public function index()
    {
        return view('user.index');
    }

    public function create()
    {
        $states = States::all();
        $countries = Countries::all();
        return view('user.create')
            ->with('states', $states)
            ->with('countries', $countries);
    }

    public function store(Request $request)
    {
        $userData = $request->only(['name', 'email', 'password']);
        $userData['password'] = bcrypt($request->password);

        $userInfoData = $request->except(['name', 'email', 'password']);

        $user = new Users();
        if ($user->addNewUser($userData, $userInfoData)) {
            return 1;
        }
        // $input = $request->all();
        // dd($input);
        // DB::beginTransaction();
        // try{
        //     Users::create($input);
        // }catch(Exception $e){
        //     DB::rollback();
        //     throw $e;
        // }
    }

    public function show($id)
    {
        $data = Users::find($id)->with('userInfo')->first();
        $data['states'] = States::all();
        $data['countries'] = Countries::all();
 
        return view('user.show')
            ->with('data', (object) $data);
    }

    public function edit($id)
    {
        $data = Users::find($id);
        // dd($data);
        $data['states'] = States::all();
        $data['countries'] = Countries::all();
 
        return view('user.edit')
            ->with('data', (object) $data);
    }

    public function update(Request $request, $id)
    {
        $userId = Users::find($id);
        $userInfoes = Userinfoes::where('user_id', $userId->id)->first();
        $input = $request->all();
        
        try{
            
            $userId->update($input);
            $userInfoes->update($input);
        }catch(Exception $e){
            throw $e;
        }
        return redirect()->route('user.index');
    }

    public function destroy($id)
    {
        DB::beginTransaction();
        try {
            if (Userinfoes::where('user_id', $id)->delete()) {
                if (Users::destroy($id)) {
                    DB::commit();

                    return redirect()->route('user.index');
                }
            }
        } catch (\Throwable $th) {
            DB::rollBack();
            throw $th;
        }

        return redirect()->route('user.index');
    }

    public function getUsers()
    {
        return Users::all();
    }

    public function getUserInfoes()
    {
        return Userinfoes::all();
    }
}

resources/views/user/add.blade.php
<div class="form-group row">
    <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>
    <div class="col-md-6">
        <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus autocomplete="off">
    </div>
</div>

<div class="form-group row">
    <label for="email" class="col-md-4 col-form-label text-md-right">Email</label>
    <div class="col-md-6">
        <input id="email" type="text" class="form-control" name="email" value="{{ old('email') }}" required autofocus autocomplete="off">
    </div>
</div>

<div class="form-group row">
    <label for="password" class="col-md-4 col-form-label text-md-right">Password</label>
    <div class="col-md-6">
        <input id="password"  type="password" class="form-control" name="password" value="{{ old('password') }}" required autofocus autocomplete="off">
    </div>
</div>

<div class="form-group row">
    <label for="full_name" class="col-md-4 col-form-label text-md-right">Fullname</label>
    <div class="col-md-6">
        <input id="full_name" type="text" class="form-control" name="full_name" value="{{ old('full_name') }}" required autofocus autocomplete="off">
    </div>
</div>

<div class="form-group row">
    <label for="gender" class="col-md-4 col-form-label text-md-right">Gender</label>
    <div class="col-md-6">
        <select id="gender" name="gender" class="form-control" required>
            <option selected disabled></option>
                <option value="Male" selected>Male</option>
                <option value="Female" selected>Female</option>
            </select>
    </div>
</div>

<div class="form-group row">
    <label for="ic_no" class="col-md-4 col-form-label text-md-right">IC No.</label>
    <div class="col-md-6">
        <input id="ic_no"  type="number" class="form-control" name="ic_no" value="{{ old('ic_no') }}" required autofocus autocomplete="off">
    </div>
</div>

<div class="form-group row">
    <label for="street" class="col-md-4 col-form-label text-md-right">Street</label>
    <div class="col-md-6">
        <input id="street" type="text" class="form-control" name="street" value="{{ old('street') }}" required autofocus autocomplete="off">
    </div>
</div>

<div class="form-group row">
    <label for="city" class="col-md-4 col-form-label text-md-right">City</label>
    <div class="col-md-6">
        <input id="city" type="text" class="form-control" name="city" value="{{ old('city') }}" required autofocus autocomplete="off">
    </div>
</div>

<div class="form-group row">
    <label for="postcode" class="col-md-4 col-form-label text-md-right">Postcode</label>
    <div class="col-md-6">
        <input id="postcode" type="number" class="form-control" name="postcode" value="{{ old('postcode') }}" required autofocus autocomplete="off">
    </div>
</div>

<div class="form-group row">
    <label for="state_id" class="col-md-4 col-form-label text-md-right">State</label>
    <div class="col-md-6">
        <select id="state_id" name="state_id" class="form-control" required>
            <option selected disabled></option>
            
            @foreach($states as $state)
            <option value="{{ $state->name }}">{{ $state->name }}</option>
            @endforeach
        </select>
    </div>
</div>

<div class="form-group row">
    <label for="country_id" class="col-md-4 col-form-label text-md-right">Country</label>
    <div class="col-md-6">
        <select id="country_id" name="country_id" class="form-control" required>
            <option selected disabled></option>
            
            @foreach($countries as $country)
            <option value="{{ $country->name }}">{{ $country->name }}</option>
            @endforeach
        </select>
    </div>
</div>

resources/views/user/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Add a New User</div>
                <div class="card-body">
                    <form action="{{ route('user.store') }} method='POST">
                    @csrf
                    @include('user.add')
                    </form>
                    <div class="form-group row mb-0">
                        <div class="col-md-6 offset-md-4">
                            <input type="submit" id="submit" value="Save" class="btn btn-primary">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script>
    $("#submit").on('click', () => {
        var url = "{{ route('user.store') }}";
        var data = $('form').serialize();
        $.post(url, data, function (response) {
            if(response) {
                window.location.href = "{{ route('user.index') }}";
            }
        });
    })
</script>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit User</div>
                <div class="card-body">
                    <?php $current_uri = request()->segments(2); ?>
                    <form>
                        @csrf
                        @method('put')
                        @include('user.fields')
                    </form>
                    <div class="form-group row mb-0">
                        <div class="col-md-6 offset-md-4">
                            <input type="button" id="submit" value="Update" class="btn btn-primary">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script>
    var id = {{ Request::segment(2) }}
    $("#submit").on('click', () => {
    
        var url = '{{ route("user.update", ":id") }}';
        url = url.replace(':id',id);
        var data = $('form').serialize();
        $.post(url, data, function (response) {
            if(response) {
                console.log(response);
                window.location.href = "{{ route('user.index') }}";
            }
        });
    })
</script>
@endsection

resources/views/user/fields.blade.php
<div class="form-group row">
    <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>
    <div class="col-md-6">
        <input id="name" value="{{ $data->name }}" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus autocomplete="off">
    </div>
</div>

<div class="form-group row">
    <label for="email" class="col-md-4 col-form-label text-md-right">Email</label>
    <div class="col-md-6">
        <input id="email" value="{{ $data->email }}" type="text" class="form-control" name="email" value="{{ old('email') }}" required autofocus autocomplete="off">
    </div>
</div>

<div class="form-group row">
    <label for="password" class="col-md-4 col-form-label text-md-right">Password</label>
    <div class="col-md-6">
        <input id="password" value="{{ $data->password }}" type="password" class="form-control" name="password" value="{{ old('password') }}" required autofocus autocomplete="off">
    </div>
</div>

<div class="form-group row">
    <label for="full_name" class="col-md-4 col-form-label text-md-right">Fullname</label>
    <div class="col-md-6">
        <input id="full_name" value="{{ $data->userInfo->full_name }}" type="text" class="form-control" name="full_name" value="{{ old('full_name') }}" required autofocus autocomplete="off">
    </div>
</div>

<div class="form-group row">
    <label for="gender" class="col-md-4 col-form-label text-md-right">Gender</label>
    <div class="col-md-6">
        <select id="gender" value="{{ $data->userInfo->gender }}" name="gender" class="form-control" required>
            <option selected disabled></option>
            
                @if($data->userInfo->gender == "Male")
                <option value="Male" selected>Male</option>
                @else
                <option value="Female" selected>Female</option>
                @endif
            </select>
    </div>
</div>

<div class="form-group row">
    <label for="ic_no" class="col-md-4 col-form-label text-md-right">IC No.</label>
    <div class="col-md-6">
        <input id="ic_no" value="{{ $data->userInfo->ic_no }}" type="text" class="form-control" name="ic_no" value="{{ old('ic_no') }}" required autofocus autocomplete="off">
    </div>
</div>

<div class="form-group row">
    <label for="street" class="col-md-4 col-form-label text-md-right">Street</label>
    <div class="col-md-6">
        <input id="street" value="{{ $data->userInfo->street }}" type="text" class="form-control" name="street" value="{{ old('street') }}" required autofocus autocomplete="off">
    </div>
</div>

<div class="form-group row">
    <label for="city" class="col-md-4 col-form-label text-md-right">City</label>
    <div class="col-md-6">
        <input id="city" value="{{ $data->userInfo->city }}" type="text" class="form-control" name="city" value="{{ old('city') }}" required autofocus autocomplete="off">
    </div>
</div>

<div class="form-group row">
    <label for="postcode" class="col-md-4 col-form-label text-md-right">Postcode</label>
    <div class="col-md-6">
        <input id="postcode" value="{{ $data->userInfo->postcode }}" type="text" class="form-control" name="postcode" value="{{ old('postcode') }}" required autofocus autocomplete="off">
    </div>
</div>

<div class="form-group row">
    <label for="state_id" class="col-md-4 col-form-label text-md-right">State</label>
    <div class="col-md-6">
        <select id="state_id" name="state_id" class="form-control" required>
            <option selected disabled></option>
            
            @foreach($data->states as $state)
            @if($state->id == $data->userInfo->state_id)
            <option value="{{ $state->id }}" selected>{{ $state->name }}</option>
            @else
            <option value="{{ $state->id }}">{{ $state->name }}</option>
            @endif
            @endforeach
        </select>
    </div>
</div>

<div class="form-group row">
    <label for="country_id" class="col-md-4 col-form-label text-md-right">Country</label>
    <div class="col-md-6">
        <select id="country_id" name="country_id" class="form-control" required>
            <option selected disabled></option>
            
            @foreach($data->countries as $country)
            @if($country->id == $data->userInfo->country_id)
            <option value="{{ $country->id }}" selected>{{ $country->name }}</option>
            @else
            <option value="{{ $country->id }}">{{ $country->name }}</option>
            @endif
            @endforeach
        </select>
    </div>
</div>

resources/views/user/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Users</div>
                <div class="card-body">
                    <a href="{{ route('user.create') }}" class="btn btn-primary">Add New User</a>
                    <table class="table">
                        <thead>
                            <tr>
                                <td>#</td>
                                <td>Name</td>
                                <td>Email</td>
                                <td>Action</td>
                            </tr>
                        </thead>
                        <tbody id="users"></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <br />
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">User Infoes</div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <td>#</td>
                                <td>Full Name</td>
                                <td>IC Number</td>
                                <td>Gender</td>
                                <td>State</td>
                            </tr>
                        </thead>
                        <tbody id="userinfo"></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    var url = "{{ route('api.get.users') }}";
    var userInfoUrl = "{{ route('api.get.userinfoes') }}";
    var deleteBtn = function(deleteUrl) {
        return '<form style="display: inline" action=' + deleteUrl + ' method="POST">{{ csrf_field() }} {{ method_field("DELETE") }}<button class="btn fa fa-trash"></button></form>';
    }
    $(() => {
        
        $.get(url, (users) => {
            var i = 1;
            $.each(users, (key, value) => {
                let tableTemplate = function(index, value) {
                    index++;
                    var showUri = `/user/${value.id}`;
                    var editUri = `/user/${value.id}/edit`;
                    return `
                        <tr>
                            <td>${index}</td>
                            <td><a href="${showUri}">${value.name}</a></td>    
                            <td>${value.email}</td>     
                            <td>
                                <a href="${editUri}" class="btn fa fa-edit"></a>
                                ${deleteBtn(showUri)}
                            </td>    
                        </tr>
                    `;
                }

                $('#users').append(tableTemplate(key, value))
            })
        });

        $.get(userInfoUrl, (userInfoes) => {
            var i = 1;
            $.each(userInfoes, (key, value) => {
                console.log(value)
                let tableTemplate = function(index, value) {
                    index++;
                    var showUri = `/userinfo/${value.id}`;
                    var editUri = `/userinfo/${value.id}/edit`;
                    return `
                        <tr>
                            <td>${index}</td>
                            <td>${value.full_name}</td>
                            <td>${value.ic_no}</td>
                            <td>${value.gender}</td>
                            <td>${value.state_id}</td>   
                        </tr>
                    `;
                }
                $('#userinfo').append(tableTemplate(key, value));
            })
        });
    });
</script>
@endsection

resources/views/user/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ $data->userInfo->full_name }}</div>
                <div class="card-body">
                    <form>
                        @include('user.fields')
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script type="text/javascript">
    $('input, select').attr('disabled', true);
</script>
@endsection